### ISSUE TITLE
SSO Application - Occurrence Misspelled

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#105]
On the list of SSOs, please fix the spelling of Occurrence.  

![image](https://cloud.githubusercontent.com/assets/5805454/3342814/0fc2eb2c-f897-11e3-946e-7540d3ef4cb2.png)

Also needs to be fixed on SSO Details:

![image](https://cloud.githubusercontent.com/assets/5805454/3342824/28c60a28-f897-11e3-83e4-3151fb94a308.png)

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Does not appear to be changed after cache cleared.

**Comment by JMurk** [comment]
Found another location where this is misspelled.  Contact info screen.

![image](https://cloud.githubusercontent.com/assets/5805454/3469308/43794a6e-02ac-11e4-953f-b221ec5918df.png)

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Still not correct in any location    "Occurrence"

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.

**Comment by rssidlowski** [comment]
When I run in Chrome, I still see the 'Occurrance' in the SSO details.

![occurranceondetails](https://cloud.githubusercontent.com/assets/5039052/3599443/b02afb02-0cee-11e4-9f91-dba49783a5c7.GIF)

**Comment by rssidlowski** [comment]
Never mind.  Cleared cache and is working fine.
