### ISSUE TITLE
SSO Application - 5-Day Report Submission

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#159]
**Issue:**  While in the field on an iPad (8.1), the application got stuck on the loading screen when trying to email the 5-day report.

**Comment by kanglu666** [comment]
fixed for dev. in sso trigger. change schema dbo to GIS_ADMIN.
PROD should be working fine.

**Comment by JMurk** [comment]
Cleared cache and it is still not working in dev.

![image](https://cloud.githubusercontent.com/assets/5805454/4753857/13478854-5aba-11e4-9f50-bb25d7b8565e.png)

**Comment by kanglu666** [comment]
working fine for me

**Comment by JMurk** [comment]
Still not working, use SSOID 3409 as a test case.

**Comment by JMurk** [comment]
Confirmed complete.
