### ISSUE TITLE
SSO Application - 5 Day Report Email

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#161]
For the 5-day report email, please set it to email

Lakeisha.Laury@baltimorecity.gov
Kumasi.Vines@baltimorecity.gov
Eloise.Black@baltimorecity.gov

in addition to those who are on it now.

**Comment by kanglu666** [comment]
done for PROD

**Comment by JMurk** [comment]
I still see only me, Amy, and Ian.

![image](https://cloud.githubusercontent.com/assets/5805454/4809869/272b7eb8-5eaf-11e4-900c-5392ead86e69.png)

**Comment by JMurk** [comment]
Confirmed complete.
