### ISSUE TITLE
SSO Application - iOS 8.1.1 bug causes app to crash when submitting email report

### ISSUE THREAD

**Issue by jday3** [JMurk/SSO-Application-Issues#168]
After investigating this bug, I have determined that it is due to a bug in the latest iOS update. It may be related to [this issue](https://github.com/jquery/jquery-mobile/issues/7685) with jQuery Mobile. If that is the case, the bug is between iOS and Sencha Touch and we will have to wait for some resolution on their side.

**Comment by JMurk** [comment]
Thanks for the update Jesse, we will have to use a work around and/or hold off on upgrading iPads when possible (if they aren't already at 8.1.1).

**Comment by JMurk** [comment]
FYI:  Just tested in 8.1.2...... Same issue.

**Comment by jday3** [comment]
I found a workaround for this. I replaced the alert box with a sencha touch message box and now it doesn't crash. This is on dev for you to test @JMurk

**Comment by JMurk** [comment]
Nice, that works.  A while ago we were having issues with the Sencha modal screens not closing after clicking OK, so we will need to keep an eye out for that issue moving forward. 

One minor change I would make, is to change the color of the header text "Email" from black to white.  It is hard to see on the iPad screen.

I say go ahead and push this to prod.

**Comment by jday3** [comment]
Okay, the font is now white and I pushed to prod

**Comment by JMurk** [comment]
The header font still appears black on prod

![image](https://cloud.githubusercontent.com/assets/5805454/5597666/573075ca-9274-11e4-9dd0-e964da12124d.png)

**Comment by jday3** [comment]
Woops, I forgot to copy over the updated css file. Should be fixed now

**Comment by JMurk** [comment]
Confirmed Complete
